Repository wrappid/profile-module, pull requests merged in 2024-07, with the labels that each got.

#64 enhancement: validation structuring
  app/validations.registry.js
  app/validations/profile.validation.js
  app/validations/test.validation.js
Labels: enhancement

#66 fix(core): :bug: profile completeness element value
  app/components/ProfileCompletenessCard.js
Labels: :art: UI

#69 fix(core): :bug: add progress percentage in circularProgressBar
  app/components/ProfileCompletenessCard.js
Labels: 🐞 bug
